Check Python, RAM and GPU

In [ ]:
import sys

print(sys.version)
assert sys.version_info[:2] == (3, 12), "Use Python 3.12 for this notebook."

!free -h
!nvidia-smi

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
               total        used        free      shared  buff/cache   available
Mem:            12Gi       3.2Gi       3.1Gi       5.0Mi       6.4Gi       9.2Gi
Swap:             0B          0B          0B
Sat Oct 17 00:57:45 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

Get editable source code

In [ ]:
%cd /content
!git clone https://github.com/studio-dots-ai/dots.tts.git
%cd /content/dots.tts
!git checkout 3cb6f94a571097b500038f1619959075282c5c98

/content
fatal: destination path 'dots.tts' already exists and is not an empty directory.
/content/dots.tts
HEAD is now at 3cb6f94 docs: announce doteBench V1.0 release (#54)

Install dots.tts

Load the model

In [ ]:
!ls -la /content/dots.tts
!find /content/dots.tts -maxdepth 2 -type d | head -30

total 108
drwxr-xr-x 10 root root  4096 Oct 17 00:49 .
drwxr-xr-x  1 root root  4096 Oct 17 00:49 ..
drwxr-xr-x  4 root root  4096 Oct 17 00:49 apps
drwxr-xr-x  2 root root  4096 Oct 17 00:49 assets
drwxr-xr-x  2 root root  4096 Oct 17 00:49 configs
drwxr-xr-x  2 root root  4096 Oct 17 00:49 constraints
drwxr-xr-x  8 root root  4096 Oct 17 00:57 .git
drwxr-xr-x  3 root root  4096 Oct 17 00:49 .github
-rw-r--r--  1 root root   457 Oct 17 00:49 .gitignore
-rw-r--r--  1 root root 11352 Oct 17 00:49 LICENSE
-rw-r--r--  1 root root  2535 Oct 17 00:49 pyproject.toml
-rw-r--r--  1 root root 46630 Oct 17 00:49 README.md
drwxr-xr-x  2 root root  4096 Oct 17 00:49 scripts
drwxr-xr-x  4 root root  4096 Oct 17 00:49 src
/content/dots.tts
/content/dots.tts/scripts
/content/dots.tts/constraints
/content/dots.tts/assets
/content/dots.tts/src
/content/dots.tts/src/dots_tts
/content/dots.tts/src/dots.tts.egg-info
/content/dots.tts/.git
/content/dots.tts/.git/branches
/content/dots.tts/.git/hooks
/content/dots.tts/.git/objects
/content/dots.tts/.git/info
/content/dots.tts/.git/logs
/content/dots.tts/.git/refs
/content/dots.tts/apps
/content/dots.tts/apps/gradio
/content/dots.tts/apps/edit_playground
/content/dots.tts/.github
/content/dots.tts/.github/workflows
/content/dots.tts/configs

In [ ]:
%cd /content

!git clone https://github.com/studio-dots-ai/dots.tts.git

%cd /content/dots.tts

!git checkout 3cb6f94a571097b500038f1619959075282c5c98

/content
fatal: destination path 'dots.tts' already exists and is not an empty directory.
/content/dots.tts
HEAD is now at 3cb6f94 docs: announce doteBench V1.0 release (#54)

Imports and resource check

In [ ]:
%cd /content/dots.tts

%pip install -e . "transformers==4.57.0" "setuptools>=68,<82" "accelerate>=1.12.0" pyarrow pandas psutil

/content/dots.tts
Obtaining file:///content/dots.tts
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: transformers==4.57.0 in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: setuptools<82,>=68 in /usr/local/lib/python3.12/dist-packages (75.2.0)
Requirement already satisfied: accelerate>=1.12.0 in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (5.9.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (3.29.7)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.0) (4.67.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0) (2.11.0+cu128)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: torchaudio>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (2.11.0+cu128)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (0.7.3)
Requirement already satisfied: langcodes[data] in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (3.5.1)
Requirement already satisfied: gradio<7,>=6.17 in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (6.17.3)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (0.8.2)
Requirement already satisfied: librosa>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (0.11.0)
Requirement already satisfied: soundfile>=0.13.1 in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (0.14.0)
Requirement already satisfied: pydantic<3,>=2.12.5 in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (2.13.4)
Requirement already satisfied: torchdiffeq in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (0.2.5)
Requirement already satisfied: lingua-language-detector in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (2.2.0)
Requirement already satisfied: WeTextProcessing in /usr/local/lib/python3.12/dist-packages (from dots.tts==0.3.1) (1.2.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (4.14.2)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.139.0)
Requirement already satisfied: gradio-client==2.5.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (2.5.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.28.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (3.0.3)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (3.11.9)
Requirement already satisfied: pillow<13.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (11.3.0)
Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.0.32)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (1.3.1)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.14.0)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.26.8)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (4.16.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio<7,>=6.17->dots.tts==0.3.1) (0.51.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==2.5.0->gradio<7,>=6.17->dots.tts==0.3.1) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.0) (1.5.1)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (0.68.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.1.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa>=0.11.0->dots.tts==0.3.1) (1.2.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.12.5->dots.tts==0.3.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.12.5->dots.tts==0.3.1) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.12.5->dots.tts==0.3.1) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.13.1->dots.tts==0.3.1) (2.1.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.12.0) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.12.0) (12.8.90)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes[data]->dots.tts==0.3.1) (1.4.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.0) (2026.6.17)
Requirement already satisfied: pynini>=2.1.6 in /usr/local/lib/python3.12/dist-packages (from WeTextProcessing->dots.tts==0.3.1) (2.1.7)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from WeTextProcessing->dots.tts==0.3.1) (7.1.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.13.1->dots.tts==0.3.1) (3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.12.0) (1.5.6)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio<7,>=6.17->dots.tts==0.3.1) (0.0.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio<7,>=6.17->dots.tts==0.3.1) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio<7,>=6.17->dots.tts==0.3.1) (0.16.0)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from language-data>=1.2->langcodes[data]->dots.tts==0.3.1) (1.4.1)
Requirement already satisfied: llvmlite<0.51,>=0.50.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa>=0.11.0->dots.tts==0.3.1) (0.50.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa>=0.11.0->dots.tts==0.3.1) (4.10.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa>=0.11.0->dots.tts==0.3.1) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.12.0) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio<7,>=6.17->dots.tts==0.3.1) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio<7,>=6.17->dots.tts==0.3.1) (13.9.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.14.0->gradio<7,>=6.17->dots.tts==0.3.1) (8.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio<7,>=6.17->dots.tts==0.3.1) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio<7,>=6.17->dots.tts==0.3.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio<7,>=6.17->dots.tts==0.3.1) (0.1.2)
Building wheels for collected packages: dots.tts
  Building editable for dots.tts (pyproject.toml) ... done
  Created wheel for dots.tts: filename=dots_tts-0.3.1-0.editable-py3-none-any.whl size=22612 sha256=7317bc9f73a1f19d81da8105c1c0cb0530c0d5a179af3a19658a044e07ed7004
  Stored in directory: /tmp/pip-ephem-wheel-cache-jtwlgfmq/wheels/d3/1c/3c/e392a43ce1368b465e6dac35a21ab086e77f1b67109bf73a59
Successfully built dots.tts
Installing collected packages: dots.tts
  Attempting uninstall: dots.tts
    Found existing installation: dots.tts 0.3.1
    Uninstalling dots.tts-0.3.1:
      Successfully uninstalled dots.tts-0.3.1
Successfully installed dots.tts-0.3.1

In [ ]:
import sys
import gc
import json
import inspect
import random
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import psutil
import soundfile as sf
from IPython.display import Audio, display
from huggingface_hub import snapshot_download

REPO = Path("/content/dots.tts")
OUT = Path("/content/rababb_kv_map")
OUT.mkdir(exist_ok=True)
SOURCE_REVISION = "3cb6f94a571097b500038f1619959075282c5c98"
assert torch.cuda.is_available(), "Enable a GPU runtime."
revision = !git -C /content/dots.tts rev-parse HEAD
assert revision[0] == SOURCE_REVISION, "Run Setup to use the expected source revision."

from dots_tts.runtime import DotsTtsRuntime
assert Path(inspect.getfile(DotsTtsRuntime)).is_relative_to(REPO)
print("GPU:", torch.cuda.get_device_name(0))
print("Available CPU RAM (GiB):", round(psutil.virtual_memory().available / 2**30, 2))
print("Available GPU memory (GiB):", round(torch.cuda.mem_get_info()[0] / 2**30, 2))

GPU: Tesla T4
Available CPU RAM (GiB): 7.04
Available GPU memory (GiB): 14.46

Optional Hugging Face login

In [ ]:
USE_HF_TOKEN = True

if USE_HF_TOKEN:
    from google.colab import userdata
    from huggingface_hub import login
    login(token=userdata.get("HF_TOKEN"), add_to_git_credential=False)

Download the weights

In [ ]:
MODEL_ID = "dots-studio/dots.tts-base"
MODEL_REVISION = "b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1"
checkpoint = Path(snapshot_download(MODEL_ID, revision=MODEL_REVISION))
print("Checkpoint ready.")

Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]

latent_stats.pt:   0%|          | 0.00/3.20k [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

llm_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/831 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/4.40G [00:00<?, ?B/s]

speaker_encoder.safetensors:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocoder.safetensors:   0%|          | 0.00/724M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Checkpoint ready.

Save the original loading functions

In [ ]:
from accelerate import init_empty_weights
from safetensors import safe_open
import dots_tts.models.dots_tts.model as model_code

Model = model_code.DotsTtsModel
original_core_constructor = model_code.DotsTtsCore
original_artifact_loader = Model._load_artifact_module
original_loader_descriptor = Model.__dict__["_load_artifact_module"]

Create an empty core

In [ ]:
def create_empty_core(*args, **kwargs):
    with init_empty_weights(include_buffers=False):
        core = original_core_constructor(*args, **kwargs)
    return core

Load checkpoint tensors one at a time

In [ ]:
def load_weights(owner, module, path):
    has_empty_parameters = any(p.is_meta for p in module.parameters())
    if not has_empty_parameters:
        return original_artifact_loader(module, path)

    with safe_open(str(path), framework="pt", device="cpu") as checkpoint_file:
        names = list(checkpoint_file.keys())

    weights = {}
    for name in names:
        with safe_open(str(path), framework="pt", device="cpu") as checkpoint_file:
            tensor = checkpoint_file.get_tensor(name)
            dtype = torch.float16 if tensor.is_floating_point() else tensor.dtype
            weights[name] = tensor.to(device="cuda", dtype=dtype)
            del tensor

    # Restore the shared embedding/output weights expected by the upstream model.
    weights = owner._restore_artifact_state_dict(weights, module)
    module.load_state_dict(weights, strict=True, assign=True)
    return module

Load once and restore the original functions

In [ ]:
if "runtime" in globals():
    del runtime
    gc.collect()
    torch.cuda.empty_cache()

try:
    model_code.DotsTtsCore = create_empty_core
    Model._load_artifact_module = classmethod(load_weights)
    runtime = DotsTtsRuntime.from_pretrained(
        str(checkpoint),
        precision="float16",
        optimize=False,
        max_generate_length=160,
        max_sequence_length=1024,
    )
finally:
    model_code.DotsTtsCore = original_core_constructor
    Model._load_artifact_module = original_loader_descriptor

runtime.model.requires_grad_(False)
for tensor in list(runtime.model.parameters()) + list(runtime.model.buffers()):
    assert not tensor.is_meta, "A checkpoint tensor was not loaded."
print("Model loaded. Sample rate:", runtime.sample_rate)
print("Core dtype:", next(runtime.model.core.parameters()).dtype)
print("Available CPU RAM (GiB):", round(psutil.virtual_memory().available / 2**30, 2))

2026-10-17 01:00:15.863 | INFO     | dots_tts.runtime:from_pretrained:160 - [runtime] Runtime load started: model=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1 revision=None cache_dir=None precision=float16
2026-10-17 01:00:15.871 | DEBUG    | dots_tts.runtime:_resolve_pretrained_path:198 - [runtime] Resolving pretrained path: model=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1 revision=None cache_dir=None
2026-10-17 01:00:15.876 | DEBUG    | dots_tts.runtime:_resolve_pretrained_path:209 - [runtime] Using local pretrained directory: path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1
2026-10-17 01:00:15.883 | DEBUG    | dots_tts.models.dots_tts.model:from_pretrained:465 - [model] DotsTtsModel load started: pretrained_path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1
2026-10-17 01:00:15.895 | DEBUG    | dots_tts.models.dots_tts.model:from_pretrained:476 - [model] DotsTtsModel config loaded: pretrained_path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1 sample_rate=48000 patch_size=4
/usr/local/lib/python3.12/dist-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2026-10-17 01:00:50.560 | INFO     | dots_tts.models.dots_tts.model:from_pretrained:496 - [model] DotsTtsModel load completed: pretrained_path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1
2026-10-17 01:00:50.584 | INFO     | dots_tts.runtime:from_pretrained:176 - [runtime] Runtime load completed: pretrained_path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1
2026-10-17 01:00:51.513 | INFO     | dots_tts.runtime:__init__:126 - [runtime] Runtime initialized: pretrained_path=/root/.cache/huggingface/hub/models--dots-studio--dots.tts-base/snapshots/b5aac65a395e04a60a8dacd4e2f4aadc5ad3dbe1 device=cuda sample_rate=48000 precision=float16 optimize=False max_audio_patch_count=160 max_sequence_length=1024 vocoder_merge_steps=4

Model loaded. Sample rate: 48000
Core dtype: torch.float16
Available CPU RAM (GiB): 2.24

Get a voice clip and generate one baseline

Download a small speech dataset file

In [ ]:
import io
import pyarrow.parquet as pq
from huggingface_hub import HfApi, list_repo_files, hf_hub_download

DATASET = "hf-internal-testing/librispeech_asr_dummy"
DATASET_REVISION = HfApi().dataset_info(DATASET).sha
filenames = list_repo_files(DATASET, repo_type="dataset", revision=DATASET_REVISION)
parquet_names = sorted(name for name in filenames if name.endswith(".parquet"))
assert parquet_names, "The dataset has no Parquet files."
reference_file = hf_hub_download(
    DATASET, parquet_names[0], repo_type="dataset", revision=DATASET_REVISION,
)

clean/validation-00000-of-00001.parquet:   0%|          | 0.00/9.19M [00:00<?, ?B/s]

Choose an intact short clip

In [ ]:
REFERENCE_AUDIO = str(OUT / "reference.wav")
REFERENCE_TEXT = None
speech_file = pq.ParquetFile(reference_file)

for batch in speech_file.iter_batches(batch_size=1, columns=["audio", "text"]):
    row = batch.to_pylist()[0]
    audio_bytes = row["audio"]["bytes"]
    if audio_bytes is None:
        continue
    waveform, sample_rate = sf.read(io.BytesIO(audio_bytes), dtype="float32")
    if waveform.ndim == 2:
        waveform = waveform.mean(axis=1)
    seconds = len(waveform) / sample_rate
    if 3 <= seconds <= 10:
        sf.write(REFERENCE_AUDIO, waveform, sample_rate)
        REFERENCE_TEXT = row["text"]
        break

assert REFERENCE_TEXT is not None, "No suitable clip found in this dataset file."
print(REFERENCE_TEXT)
display(Audio(REFERENCE_AUDIO))
del speech_file, batch, row, waveform, audio_bytes

MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL

One generation function

In [ ]:
TEXT = "Hello, this is a test of the dots TTS model."
SEED = 42
STEPS = 10

def generate(steps=STEPS, profile=False):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)
    with torch.inference_mode():
        return runtime.generate(
            text=TEXT,
            prompt_audio_path=REFERENCE_AUDIO,
            prompt_text=REFERENCE_TEXT,
            num_steps=steps,
            ode_method="euler",
            guidance_scale=1.2,
            speaker_scale=1.5,
            profile_inference=profile,
        )

Generate, save and listen

In [ ]:
baseline = generate(profile=True)
baseline_audio = baseline["audio"].detach().float().cpu().squeeze().numpy()
assert np.isfinite(baseline_audio).all(), "Audio has invalid values."
sf.write(OUT / "baseline.wav", baseline_audio, baseline["sample_rate"])
baseline_profile = baseline["profiling"]
display(Audio(str(OUT / "baseline.wav")))
display(pd.DataFrame(baseline_profile).T)
del baseline

2026-10-17 01:00:54.238 | DEBUG    | dots_tts.runtime:_load_prompt_audio:447 - [io] Loading prompt audio: path=/content/rababb_kv_map/reference.wav
2026-10-17 01:01:19.433 | DEBUG    | dots_tts.runtime:_load_prompt_audio:458 - [io] Prompt audio loaded: path=/content/rababb_kv_map/reference.wav original_sample_rate=16000 resampled_sample_rate=48000 samples=238080
2026-10-17 01:01:19.441 | INFO     | dots_tts.data.pipelines.tokenizing:build_generation_schedule:211 - Built generation schedule: interleave=False max_audio_tokens=160 sequence='[文本]MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL\nHello, this is a test of the dots TTS model.[文本对应语音]<|audio_gen_start|>'
2026-10-17 01:01:19.445 | DEBUG    | dots_tts.runtime:_prepare_inputs:641 - [request] Inputs prepared: request_id=d8e2b5aeeff96d5a template_name=tts language=None text_len=44 prompt_text_len=90 schedule_length=212 prompt_audio_patch_count=31 max_audio_patch_count=160 max_sequence_length=1024 has_prompt_audio=True
2026-10-17 01:01:19.445 | DEBUG    | dots_tts.runtime:generate:831 - [request] Generation started: request_id=d8e2b5aeeff96d5a text_len=44 has_prompt_audio=True has_prompt_text=True template_name=tts language=None precision=float16 ode_method=euler num_steps=10 guidance_scale=1.2 speaker_scale=1.5 max_audio_patch_count=160 normalize_text=False
2026-10-17 01:01:22.246 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:936 - [conditioning] Prompt conditioning prepared: prompt_samples=238080 prompt_patch_count=30 speaker_scale=1.5 device=cuda:0
2026-10-17 01:01:22.398 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1429 - [decode] Latent generation prepared: schedule_audio_spans=160 prompt_patch_count=30 minimum_required_spans=31
2026-10-17 01:01:26.422 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=1
2026-10-17 01:01:29.536 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=10
2026-10-17 01:01:32.535 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=20
2026-10-17 01:01:32.855 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1499 - [decode] Latent generation completed: payload_audio_patches=21
2026-10-17 01:01:32.856 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1609 - [vocoder] Vocoder decode started: latent_patch_count=21
2026-10-17 01:01:33.516 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1616 - [vocoder] Vocoder decode completed: waveform_samples=161280
2026-10-17 01:01:33.518 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=FM seconds=8.0521 count=22 rtf=2.3965
2026-10-17 01:01:33.519 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=latent_encoder seconds=0.2355 count=1 rtf=0.0701
2026-10-17 01:01:33.520 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=patch_encoder seconds=1.0122 count=23 rtf=0.3012
2026-10-17 01:01:33.522 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=LLM seconds=1.1512 count=23 rtf=0.3426
2026-10-17 01:01:33.523 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=latent_decoder seconds=0.6590 count=1 rtf=0.1961
2026-10-17 01:01:33.523 | INFO     | dots_tts.utils.profiling:log_inference_profile:271 - [profile] Inference profiling: request_id=d8e2b5aeeff96d5a stage=speaker_encoder seconds=2.1773 count=1 rtf=0.6480
2026-10-17 01:01:33.524 | INFO     | dots_tts.runtime:generate:885 - [request] Generation completed: request_id=d8e2b5aeeff96d5a elapsed_seconds=14.071 audio_seconds=3.360 rtf=4.1879 sample_rate=48000

                  seconds  count       rtf
FM               8.052093   22.0  2.396456
latent_encoder   0.235461    1.0  0.070078
patch_encoder    1.012170   23.0  0.301241
LLM              1.151244   23.0  0.342632
latent_decoder   0.658954    1.0  0.196117
speaker_encoder  2.177253    1.0  0.647992
vocoder          0.000000    0.0  0.000000

Read the inference path

Open the high-level model path

In [ ]:
from dots_tts.modules.backbone.dit_inference import EagerDiTRunner, DiTSolver, CachedDiTRunner
from dots_tts.modules.backbone.llm_inference import LLMInference

print("Runtime file:", inspect.getfile(DotsTtsRuntime))
print("Model file:", inspect.getfile(type(runtime.model)))
for name, module in runtime.model.named_children():
    print(name, "->", type(module).__name__)
print(inspect.getsource(runtime.model.generate_audio))

Runtime file: /content/dots.tts/src/dots_tts/runtime.py
Model file: /content/dots.tts/src/dots_tts/models/dots_tts/model.py
core -> DotsTtsCore
vocoder -> AudioVAE
xvector_extractor -> SpeakerXVectorFeatures
    @torch.no_grad()
    def generate_audio(
        self,
        data: dict[str, Any],
        *,
        precision: str,
        ode_method: str,
        num_steps: int,
        guidance_scale: float,
        speaker_scale: float = 1.5,
    ) -> torch.Tensor:
        latent_patches = list(
            self._generate_latents_stream(
                data,
                precision=precision,
                ode_method=ode_method,
                num_steps=num_steps,
                guidance_scale=guidance_scale,
                speaker_scale=speaker_scale,
            )
        )
        logger.debug(
            logc("vocoder", "Vocoder decode started: latent_patch_count={}"),
            len(latent_patches),
        )
        audio = self._get_vocoder_inference().decode_latents(
            torch.cat(latent_patches, dim=1)
        )
        logger.debug(
            logc("vocoder", "Vocoder decode completed: waveform_samples={}"),
            audio.shape[-1],
        )
        return audio

Follow one audio-patch decode

In [ ]:
print(inspect.getsource(runtime.model._decode_next_audio))
print(inspect.getsource(runtime.model._consume_audio_patch))

    def _decode_next_audio(
        self,
        state: _GenerateState,
        *,
        g_cond: torch.Tensor | None,
        ode_method: str,
        num_steps: int,
        guidance_scale: float,
        profile_step: int | None = None,
    ) -> torch.Tensor:
        with measure_inference("FM", phase="decode", step=profile_step):
            sequence = state.fm_sequence
            if sequence is None:
                raise RuntimeError("FM static buffer is not initialized.")
            null_g_cond = state.fm_null_g_cond
            if null_g_cond is None:
                raise RuntimeError("FM null conditioning buffer is not initialized.")
            sampling = self.config.sampling
            if sampling is not None:
                sampling.resolve(
                    ode_method=ode_method,
                    num_steps=num_steps,
                    guidance_scale=guidance_scale,
                )
            solver_mode = sampling.solver if sampling is not None else self.core.mode
            cfg_sequence = state.fm_cfg_sequence
            if solver_mode == "flow_matching" and cfg_sequence is None:
                raise RuntimeError("FM cfg static buffer is not initialized.")
            solver_cfg_sequence = (
                cfg_sequence if solver_mode == "flow_matching" else None
            )
            audio_patch = self._get_dit_solver(solver_mode=solver_mode).decode_next(
                state.fm_dit_state,
                sequence=sequence,
                cfg_sequence=solver_cfg_sequence,
                fm_seq_len=state.fm_seq_len,
                null_g_cond=null_g_cond,
                g_cond=g_cond,
                nfe=num_steps,
                ode_method=ode_method,
                guidance_scale=guidance_scale,
            )
            return audio_patch

    def _consume_audio_patch(
        self,
        state: _GenerateState,
        *,
        audio_patch: torch.Tensor,
        profile_step: int | None = None,
    ) -> None:
        audio_patch_for_llm = self._prepare_patch_encoder_input(
            audio_patch,
            already_normalized=True,
        )
        self._append_history_chunk(state, audio_patch)
        state_dtype = (
            state.fm_sequence.dtype
            if state.fm_sequence is not None
            else audio_patch_for_llm.dtype
        )
        with measure_inference("patch_encoder", phase="decode", step=profile_step):
            llm_embedding, state.patch_encoder_state = (
                self._get_patch_encoder_inference().decode_patch_with_state(
                    audio_patch_for_llm,
                    state.patch_encoder_state,
                    optimize=self._optimize_enabled,
                    bucket_resolver=self._resolve_generate_length_bucket,
                    dtype=state_dtype,
                )
            )
        with measure_inference("LLM", phase="decode", step=profile_step):
            _, state.llm_hiddens, _logits = self._get_llm_inference().step(
                state.llm_state,
                inputs_embeds=llm_embedding,
                request_logits=False,
                compile_static=True,
                optimize=self._optimize_enabled,
                max_sequence_length=self._llm_max_sequence_length,
            )

In [ ]:
# Phase 1: trace the DiT / solver inference path

import inspect

print("===== DiTSolver =====")
print(inspect.getsource(DiTSolver))

print("\n===== EagerDiTRunner =====")
print(inspect.getsource(EagerDiTRunner))

===== DiTSolver =====
class DiTSolver:
    """Streaming DiT decoder with a KV cache across ODE steps (optimize mode).

    In non-optimize mode this delegates to :class:`EagerDiTRunner`. In
    optimize mode it maintains a per-bucket :class:`CachedDiTRunner` and
    incrementally warms a :class:`DiTKvCache`.
    """

    def __init__(
        self,
        context: DiTInferenceContext,
        *,
        optimize: bool,
        bucket_resolver: Callable[[int], int],
        meanflow: bool = False,
    ):
        self.context = context
        self.optimize = bool(optimize)
        self.bucket_resolver = bucket_resolver
        self.meanflow = bool(meanflow)
        self.branch_multiplier = 1 if self.meanflow else 2
        self._cached_runners: dict[tuple[Any, ...], CachedDiTRunner] = {}
        self._eager_runners: dict[tuple[Any, ...], EagerDiTRunner] = {}
        self._backend_by_device_type: dict[str, str] = {}

    # ---- Runner lookup -------------------------------------------------- #

    def _resolve_bucket_patches(self, fm_seq_len: int) -> int:
        requested = int(fm_seq_len)
        if requested <= 0:
            raise ValueError("fm_seq_len must be positive.")
        requested_patch_count = max(
            1, (requested + self.context.unit_len - 1) // self.context.unit_len
        )
        if not self.optimize:
            return requested_patch_count
        return int(self.bucket_resolver(requested_patch_count))

    def _backend_for(self, device: torch.device) -> str:
        key = device.type
        if key not in self._backend_by_device_type:
            self._backend_by_device_type[key] = _resolve_kv_attention_backend(
                optimize=self.optimize, on_cuda=(key == "cuda")
            )
        return self._backend_by_device_type[key]

    def _get_cached_runner(
        self, *, capacity_patches: int, device: torch.device, dtype: torch.dtype
    ) -> CachedDiTRunner:
        backend = self._backend_for(device)
        capacity_tokens = int(capacity_patches) * self.context.unit_len
        compile_step = bool(self.optimize and device.type == "cuda")
        key = (int(capacity_patches), str(device), dtype, backend, compile_step)
        runner = self._cached_runners.get(key)
        if runner is None:
            runner = CachedDiTRunner(
                context=self.context,
                capacity_patches=int(capacity_patches),
                capacity_tokens=capacity_tokens,
                dtype=dtype,
                device=device,
                attn_backend=backend,
                compile_step=compile_step,
                branch_multiplier=self.branch_multiplier,
            )
            self._cached_runners[key] = runner
        return runner

    def _get_eager_runner(
        self, *, device: torch.device, dtype: torch.dtype
    ) -> EagerDiTRunner:
        key = (str(device), dtype)
        runner = self._eager_runners.get(key)
        if runner is None:
            runner = EagerDiTRunner(context=self.context)
            self._eager_runners[key] = runner
        return runner

    # ---- Cache management ----------------------------------------------- #

    def _ensure_cache(
        self,
        state: DiTSolverState,
        *,
        sequence: torch.Tensor,
        nfe: int,
    ) -> tuple[CachedDiTRunner, DiTKvCache]:
        capacity_patches = self._resolve_bucket_patches(sequence.size(1))
        runner = self._get_cached_runner(
            capacity_patches=capacity_patches,
            device=sequence.device,
            dtype=sequence.dtype,
        )
        branch_batch = self.branch_multiplier * int(sequence.size(0))
        if (
            isinstance(state.cache, DiTKvCache)
            and state.cache.capacity_patches == runner.capacity_patches
            and state.cache.capacity_tokens == runner.capacity_tokens
            and state.cache.nfe == int(nfe)
            and int(state.cache.cache_k.size(2)) == branch_batch
        ):
            return runner, state.cache

        next_cache = runner.allocate_cache(batch_size=sequence.size(0), nfe=int(nfe))
        if (
            isinstance(state.cache, DiTKvCache)
            and state.cache.nfe == int(nfe)
            and int(state.cache.cache_k.size(2)) == branch_batch
        ):
            next_cache.copy_prefix_from(state.cache)
        state.cache = next_cache
        return runner, next_cache

    # ---- Schedule / mods preparation ------------------------------------ #

    def _prepare_schedule(
        self,
        state: DiTSolverState,
        *,
        g_cond: torch.Tensor,
        nfe: int,
    ) -> tuple[torch.Tensor, ODESchedule]:
        """Compute (and cache) the per-ODE-step AdaLN mods and the time grid.

        Cached across streaming decode calls as long as ``nfe`` doesn't change.
        ``g_cond`` is assumed constant within one generation (it's derived once
        from the prompt). The solver itself is per-mode so ``state`` never sees
        a schedule from the other mode.
        """
        cached_valid = (
            state.all_mods_by_ode is not None
            and state.schedule is not None
            and int(state.all_mods_by_ode.size(0)) == int(nfe)
        )
        if cached_valid:
            assert state.all_mods_by_ode is not None and state.schedule is not None
            return state.all_mods_by_ode, state.schedule

        if self.meanflow:
            all_mods, schedule = self._prepare_schedule_meanflow(g_cond=g_cond, nfe=nfe)
        else:
            all_mods, schedule = self._prepare_schedule_flow_matching(
                g_cond=g_cond, nfe=nfe
            )
        state.all_mods_by_ode = all_mods
        state.schedule = schedule
        return all_mods, schedule

    def _prepare_schedule_meanflow(
        self, *, g_cond: torch.Tensor, nfe: int
    ) -> tuple[torch.Tensor, ODESchedule]:
        dit = self.context.dit
        device, dtype = g_cond.device, g_cond.dtype
        nfe = int(nfe)
        batch_size = int(g_cond.size(0))

        times_grid = torch.linspace(0.0, 1.0, nfe + 1, device=device, dtype=dtype)
        times = times_grid[:-1]
        durations = times_grid[1:] - times

        with torch.no_grad():
            t_t = times[:, None].expand(nfe, batch_size).reshape(-1)
            c = dit.time_embedder(t_t)
            if dit.duration_embedder is not None:
                dt_t = durations[:, None].expand(nfe, batch_size).reshape(-1)
                c = c + dit.duration_embedder(dt_t)
            g_flat = g_cond[None].expand(nfe, -1, -1).reshape(nfe * batch_size, -1)
            mods = dit.fused_adaln(c + g_flat)
        return (
            mods.reshape(nfe, batch_size, -1),
            ODESchedule(mode=MEANFLOW_MODE, times=times, durations=durations),
        )

    def _prepare_schedule_flow_matching(
        self, *, g_cond: torch.Tensor, nfe: int
    ) -> tuple[torch.Tensor, ODESchedule]:
        dit = self.context.dit
        device, dtype = g_cond.device, g_cond.dtype
        nfe = int(nfe)
        g_branches = torch.cat([g_cond, torch.zeros_like(g_cond)], dim=0)
        branch_batch = int(g_branches.size(0))

        times = torch.arange(nfe, device=device, dtype=dtype) / nfe
        with torch.no_grad():
            t_t = times[:, None].expand(nfe, branch_batch).reshape(-1)
            g_flat = (
                g_branches[None].expand(nfe, -1, -1).reshape(nfe * branch_batch, -1)
            )
            mods = dit.fused_adaln(dit.time_embedder(t_t) + g_flat)
        return (
            mods.reshape(nfe, branch_batch, -1),
            ODESchedule(mode=FLOW_MATCHING_MODE, times=times),
        )

    # ---- Public entrypoint ---------------------------------------------- #

    def decode_next(
        self,
        state: DiTSolverState,
        *,
        sequence: torch.Tensor,
        fm_seq_len: int,
        null_g_cond: torch.Tensor,
        g_cond: torch.Tensor | None,
        nfe: int,
        cfg_sequence: torch.Tensor | None = None,
        ode_method: str = "euler",
        guidance_scale: float | None = None,
    ) -> torch.Tensor:
        self._validate_decode_args(
            fm_seq_len=fm_seq_len,
            nfe=nfe,
            cfg_sequence=cfg_sequence,
            guidance_scale=guidance_scale,
        )
        g_cond = (
            null_g_cond
            if g_cond is None
            else g_cond.to(device=null_g_cond.device, dtype=sequence.dtype)
        )

        if not self.optimize:
            runner = self._get_eager_runner(
                device=sequence.device, dtype=sequence.dtype
            )
            return runner.decode_next(
                sequence=sequence,
                cfg_sequence=cfg_sequence,
                fm_seq_len=int(fm_seq_len),
                g_cond=g_cond,
                nfe=int(nfe),
                meanflow=self.meanflow,
                ode_method=ode_method,
                guidance_scale=guidance_scale,
            )
        return self._decode_optimized(
            state,
            sequence=sequence,
            cfg_sequence=cfg_sequence,
            fm_seq_len=int(fm_seq_len),
            g_cond=g_cond,
            nfe=int(nfe),
            guidance_scale=guidance_scale,
        )

    # ---- Optimized (KV cache + compile) path ---------------------------- #

    def _validate_decode_args(
        self,
        *,
        fm_seq_len: int,
        nfe: int,
        cfg_sequence: torch.Tensor | None,
        guidance_scale: float | None,
    ) -> None:
        if int(nfe) <= 0:
            raise ValueError(f"nfe must be positive, got {nfe}.")
        if int(fm_seq_len) <= 0:
            raise RuntimeError(
                "Cannot decode audio before any conditioning state has been prefetched."
            )
        if self.meanflow:
            if cfg_sequence is not None:
                raise ValueError("MeanFlow DiTSolver does not accept cfg_sequence.")
        else:
            if cfg_sequence is None:
                raise ValueError("FlowMatching DiTSolver requires cfg_sequence.")
            if guidance_scale is None:
                raise ValueError("FlowMatching DiTSolver requires guidance_scale.")

    def _decode_optimized(
        self,
        state: DiTSolverState,
        *,
        sequence: torch.Tensor,
        cfg_sequence: torch.Tensor | None,
        fm_seq_len: int,
        g_cond: torch.Tensor,
        nfe: int,
        guidance_scale: float | None,
    ) -> torch.Tensor:
        hidden_patch_size = int(self.context.hidden_patch_size)
        unit_len = int(self.context.unit_len)
        prefix_len = fm_seq_len - hidden_patch_size
        if prefix_len < 0:
            raise RuntimeError(
                "FM sequence does not contain the current hidden patch: "
                f"fm_seq_len={fm_seq_len} hidden_patch_size={hidden_patch_size}."
            )
        if prefix_len % unit_len != 0:
            name = "MeanFlow DiTSolver" if self.meanflow else "FlowMatching DiTSolver"
            raise RuntimeError(
                f"{name} expects finalized history to be unit-aligned: "
                f"prefix_len={prefix_len} unit_len={unit_len}."
            )

        batch_size = int(sequence.size(0))
        current_hidden = sequence[:, prefix_len : prefix_len + hidden_patch_size]
        cfg_current_hidden = (
            None
            if cfg_sequence is None
            else cfg_sequence[:, prefix_len : prefix_len + hidden_patch_size]
        )
        z = torch.randn(
            (
                batch_size,
                int(self.context.latent_patch_size),
                self.context.noise_latent_dim,
            ),
            dtype=sequence.dtype,
            device=sequence.device,
        )
        all_mods_by_ode, schedule = self._prepare_schedule(
            state, g_cond=g_cond, nfe=nfe
        )
        guidance = (
            None if self.meanflow else sequence.new_tensor(float(guidance_scale))  # type: ignore[arg-type]
        )
        flow_dt = None if self.meanflow else sequence.new_tensor(1.0 / nfe)

        if prefix_len == 0:
            return self._decode_first_patch(
                z,
                current_hidden=current_hidden,
                cfg_current_hidden=cfg_current_hidden,
                fm_seq_len=fm_seq_len,
                all_mods_by_ode=all_mods_by_ode,
                schedule=schedule,
                sequence=sequence,
                nfe=nfe,
                batch_size=batch_size,
                guidance=guidance,
                flow_dt=flow_dt,
            )
        return self._decode_with_kv_cache(
            z,
            state=state,
            sequence=sequence,
            cfg_sequence=cfg_sequence,
            fm_seq_len=fm_seq_len,
            prefix_len=prefix_len,
            current_hidden=current_hidden,
            cfg_current_hidden=cfg_current_hidden,
            all_mods_by_ode=all_mods_by_ode,
            schedule=schedule,
            nfe=nfe,
            batch_size=batch_size,
            guidance=guidance,
            flow_dt=flow_dt,
        )

    def _decode_first_patch(
        self,
        z: torch.Tensor,
        *,
        current_hidden: torch.Tensor,
        cfg_current_hidden: torch.Tensor | None,
        fm_seq_len: int,
        all_mods_by_ode: torch.Tensor,
        schedule: ODESchedule,
        sequence: torch.Tensor,
        nfe: int,
        batch_size: int,
        guidance: torch.Tensor | None,
        flow_dt: torch.Tensor | None,
    ) -> torch.Tensor:
        runner = self._get_cached_runner(
            capacity_patches=self._resolve_bucket_patches(fm_seq_len),
            device=sequence.device,
            dtype=sequence.dtype,
        )
        for ode_idx in range(nfe):
            kwargs = {
                "current_hidden": current_hidden,
                "all_mods": all_mods_by_ode[ode_idx],
                **schedule.step_kwargs(ode_idx),
            }
            if not self.meanflow:
                kwargs.update(
                    cfg_current_hidden=cfg_current_hidden,
                    guidance_scale=guidance,
                )
            vt = runner.current_step(z, **kwargs)
            z = schedule.advance(
                z,
                vt,
                ode_idx=ode_idx,
                batch_size=batch_size,
                flow_dt=flow_dt,
            )
        return z

    def _decode_with_kv_cache(
        self,
        z: torch.Tensor,
        *,
        state: DiTSolverState,
        sequence: torch.Tensor,
        cfg_sequence: torch.Tensor | None,
        fm_seq_len: int,
        prefix_len: int,
        current_hidden: torch.Tensor,
        cfg_current_hidden: torch.Tensor | None,
        all_mods_by_ode: torch.Tensor,
        schedule: ODESchedule,
        nfe: int,
        batch_size: int,
        guidance: torch.Tensor | None,
        flow_dt: torch.Tensor | None,
    ) -> torch.Tensor:
        unit_len = int(self.context.unit_len)
        persistent_len = prefix_len - unit_len
        prev_unit = sequence[:, persistent_len:prefix_len]
        cfg_prev_unit = (
            None if cfg_sequence is None else cfg_sequence[:, persistent_len:prefix_len]
        )
        runner, kv_cache = self._ensure_cache(
            state, sequence=sequence[:, :fm_seq_len], nfe=nfe
        )
        if kv_cache.valid_tokens != persistent_len:
            runner.prefill(
                kv_cache=kv_cache,
                prefix_sequence=sequence[:, :persistent_len],
                cfg_prefix_sequence=(
                    None if cfg_sequence is None else cfg_sequence[:, :persistent_len]
                ),
                all_mods_by_ode=all_mods_by_ode,
            )
        block_mask, sdpa_mask = runner.masks_for(valid_persistent_tokens=persistent_len)
        rotary_cos, rotary_sin = runner.rotary_for(start_pos=persistent_len)
        dst = slice(persistent_len, prefix_len)

        for ode_idx in range(nfe):
            kwargs = {
                "prev_unit": prev_unit,
                "current_hidden": current_hidden,
                "all_mods": all_mods_by_ode[ode_idx],
                "cache_k": kv_cache.cache_k[ode_idx],
                "cache_v": kv_cache.cache_v[ode_idx],
                "block_mask": block_mask,
                "sdpa_mask": sdpa_mask,
                "rotary_cos": rotary_cos,
                "rotary_sin": rotary_sin,
                **schedule.step_kwargs(ode_idx),
            }
            if not self.meanflow:
                kwargs.update(
                    cfg_prev_unit=cfg_prev_unit,
                    cfg_current_hidden=cfg_current_hidden,
                    guidance_scale=guidance,
                )
            vt, new_k, new_v = runner.step(z, **kwargs)
            z = schedule.advance(
                z,
                vt,
                ode_idx=ode_idx,
                batch_size=batch_size,
                flow_dt=flow_dt,
            )
            kv_cache.cache_k[ode_idx, :, :, :, dst, :].copy_(new_k)
            kv_cache.cache_v[ode_idx, :, :, :, dst, :].copy_(new_v)
        kv_cache.valid_tokens = prefix_len
        return z


===== EagerDiTRunner =====
class EagerDiTRunner:
    """Reference decoder used when compilation/optimization is disabled.

    No KV cache, no bucketing — every ODE step reruns the full stack. This is
    what ``torchdiffeq.odeint`` drives for FlowMatching.
    """

    def __init__(self, *, context: DiTInferenceContext):
        self.context = context
        self.dit = context.dit
        self.coordinate_proj = context.coordinate_proj
        self.hidden_patch_size = int(context.hidden_patch_size)
        self.latent_patch_size = int(context.latent_patch_size)
        self.latent_dim = int(context.noise_latent_dim)
        self.hidden_size = int(context.hidden_size)
        self.fm_sigma = float(context.fm_sigma)

    # ---- Static per-decode inputs --------------------------------------- #

    def _build_decode_mask(
        self, *, total_len: int, fm_seq_len: int, device: torch.device
    ) -> torch.Tensor:
        mask = torch.zeros((1, total_len, total_len), dtype=torch.bool, device=device)
        latent_start = total_len - self.latent_patch_size
        block_start = int(fm_seq_len) - self.hidden_patch_size
        if block_start > 0:
            mask[:, :block_start, :block_start] = (
                torch.ones((block_start, block_start), dtype=torch.bool, device=device)
                .triu(1)
                .logical_not()
            )
        mask[:, block_start:fm_seq_len, :fm_seq_len] = True
        mask[:, block_start:fm_seq_len, latent_start:] = True
        mask[:, latent_start:, :fm_seq_len] = True
        mask[:, latent_start:, latent_start:] = True
        return mask

    def _build_pos_ids(
        self, *, total_len: int, fm_seq_len: int, device: torch.device
    ) -> torch.Tensor:
        pos_ids = torch.zeros((1, total_len), dtype=torch.float32, device=device)
        latent_start = total_len - self.latent_patch_size
        pos_ids[:, :fm_seq_len] = torch.arange(
            fm_seq_len, dtype=pos_ids.dtype, device=device
        )
        pos_ids[:, latent_start:] = torch.arange(
            fm_seq_len,
            fm_seq_len + self.latent_patch_size,
            dtype=pos_ids.dtype,
            device=device,
        )
        return pos_ids

    def _prepare_inputs(
        self,
        *,
        sequence: torch.Tensor,
        fm_seq_len: int,
        cfg_sequence: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor | None, torch.Tensor, torch.Tensor]:
        fm_seq_len = int(fm_seq_len)
        total_len = fm_seq_len + self.latent_patch_size

        def _pad(src: torch.Tensor) -> torch.Tensor:
            padded = src.new_zeros(src.size(0), total_len, self.hidden_size)
            padded[:, :fm_seq_len].copy_(src[:, :fm_seq_len])
            return padded

        input_sequence = _pad(sequence)

## Phase 1 Takeaways — Inference Path / NFE

- The current baseline runs with `optimize=False`, so inference uses `EagerDiTRunner`, not the KV-cached optimized path.
- The important flow is:

  runtime.generate()
      ↓
  model.generate_audio()
      ↓
  DiTSolver.decode_next()
      ↓
  EagerDiTRunner.decode_next()
      ↓
  _decode_flow_matching()
      ↓
  odeint(...)
      ↓
  solver(t, z)
      ↓
  _flow_matching_velocity()
      ↓
  self.dit(...)

- `nfe` controls the ODE solver step size for Euler as `1 / nfe`.
- The repeated heavy neural-network computation happens inside `self.dit(...)`.
- The loop is not written directly as `for step in range(nfe)` for FlowMatching; it is handled internally by `odeint(...)`.
- Before repeated solver evaluations, inputs such as `input_sequence`, `cfg_input_sequence`, `attn_mask`, `pos_ids`, `g_cond`, and guidance are prepared once.
- During inference, `t` (time) and `z` (current latent state) change across solver evaluations.
- This gives us the first useful split for Phase 2:
  - likely invariant/reusable state → conditioning, masks, position IDs, guidance-related inputs
  - changing state → timestep `t`, latent `z`, and model outputs
- The optimized path contains an explicit KV cache, but the current baseline does not use it. That path can be studied later when comparing reusable state and optimized execution.

** NFE (Number of functional Evaluations) determines how many refinement/function-evaluation steps are performed, and each evaluation eventually calls the DiT model through self.dit(...).

In [ ]:
# Phase 2A — runtime tracing for eager FlowMatching path

import types
import torch

solver = runtime.model._get_dit_solver(solver_mode="flow_matching")

runner = solver._get_eager_runner(
    device=next(runtime.model.parameters()).device,
    dtype=next(runtime.model.parameters()).dtype,
)

trace_rows = []
eval_counter = {"count": 0}

original_fmv = runner._flow_matching_velocity

def traced_flow_matching_velocity(self, t, z, **kwargs):
    eval_counter["count"] += 1
    i = eval_counter["count"]

    def info(name, x):
        if x is None:
            return {
                "eval": i,
                "name": name,
                "shape": None,
                "dtype": None,
                "device": None,
                "data_ptr": None,
                "mean": None,
            }

        return {
            "eval": i,
            "name": name,
            "shape": tuple(x.shape),
            "dtype": str(x.dtype),
            "device": str(x.device),
            "data_ptr": x.data_ptr() if x.numel() > 0 else None,
            "mean": float(x.float().mean().item()) if x.numel() > 0 else None,
        }

    trace_rows.extend([
        info("t", t),
        info("z", z),
        info("input_sequence", kwargs["input_sequence"]),
        info("g_cond", kwargs["g_cond"]),
        info("attn_mask", kwargs["attn_mask"]),
        info("pos_ids", kwargs["pos_ids"]),
    ])

    return original_fmv(t, z, **kwargs)

runner._flow_matching_velocity = types.MethodType(
    traced_flow_matching_velocity,
    runner
)

# Run one reproducible baseline
result = generate(steps=10, profile=False)

# Restore original method
runner._flow_matching_velocity = original_fmv

print("Actual function evaluations:", eval_counter["count"])

trace_df = pd.DataFrame(trace_rows)
display(trace_df)

2026-10-17 01:01:33.720 | DEBUG    | dots_tts.runtime:_load_prompt_audio:447 - [io] Loading prompt audio: path=/content/rababb_kv_map/reference.wav
2026-10-17 01:01:33.729 | DEBUG    | dots_tts.runtime:_load_prompt_audio:458 - [io] Prompt audio loaded: path=/content/rababb_kv_map/reference.wav original_sample_rate=16000 resampled_sample_rate=48000 samples=238080
2026-10-17 01:01:33.731 | INFO     | dots_tts.data.pipelines.tokenizing:build_generation_schedule:211 - Built generation schedule: interleave=False max_audio_tokens=160 sequence='[文本]MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL\nHello, this is a test of the dots TTS model.[文本对应语音]<|audio_gen_start|>'
2026-10-17 01:01:33.732 | DEBUG    | dots_tts.runtime:_prepare_inputs:641 - [request] Inputs prepared: request_id=d8e2b5aeeff96d5a template_name=tts language=None text_len=44 prompt_text_len=90 schedule_length=212 prompt_audio_patch_count=31 max_audio_patch_count=160 max_sequence_length=1024 has_prompt_audio=True
2026-10-17 01:01:33.733 | DEBUG    | dots_tts.runtime:generate:831 - [request] Generation started: request_id=d8e2b5aeeff96d5a text_len=44 has_prompt_audio=True has_prompt_text=True template_name=tts language=None precision=float16 ode_method=euler num_steps=10 guidance_scale=1.2 speaker_scale=1.5 max_audio_patch_count=160 normalize_text=False
2026-10-17 01:01:33.742 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:890 - [conditioning] Prompt speaker cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:33.744 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:920 - [conditioning] Prompt latent cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:33.745 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:936 - [conditioning] Prompt conditioning prepared: prompt_samples=238080 prompt_patch_count=30 speaker_scale=1.5 device=cuda:0
2026-10-17 01:01:33.747 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1429 - [decode] Latent generation prepared: schedule_audio_spans=160 prompt_patch_count=30 minimum_required_spans=31
2026-10-17 01:01:34.425 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=1
2026-10-17 01:01:37.231 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=10
2026-10-17 01:01:41.089 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=20
2026-10-17 01:01:41.385 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1499 - [decode] Latent generation completed: payload_audio_patches=21
2026-10-17 01:01:41.387 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1609 - [vocoder] Vocoder decode started: latent_patch_count=21
2026-10-17 01:01:41.677 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1616 - [vocoder] Vocoder decode completed: waveform_samples=161280
2026-10-17 01:01:41.680 | INFO     | dots_tts.runtime:generate:885 - [request] Generation completed: request_id=d8e2b5aeeff96d5a elapsed_seconds=7.946 audio_seconds=3.360 rtf=2.3648 sample_rate=48000

Actual function evaluations: 220

,eval,name,shape,dtype,device,data_ptr,mean
0,1,t,(),torch.float16,cuda:0,134176414100992,0.000000
1,1,z,"(1, 4, 128)",torch.float16,cuda:0,134180908194304,-0.048102
2,1,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
3,1,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
4,1,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
...,...,...,...,...,...,...,...
1315,220,z,"(1, 4, 128)",torch.float16,cuda:0,134177798224896,0.017858
1316,220,input_sequence,"(1, 260, 1024)",torch.float16,cuda:0,134176443465728,-0.011420
1317,220,g_cond,"(1, 1024)",torch.float16,cuda:0,134176187611136,-0.069792
1318,220,attn_mask,"(1, 260, 260)",torch.bool,cuda:0,134177762943488,0.502071
1319,220,pos_ids,"(1, 260)",torch.float32,cuda:0,134177798214656,129.500000

In [ ]:
# Summarize each variable
summary = []

for name, group in trace_df.groupby("name"):
    summary.append({
        "variable": name,
        "shape": group["shape"].iloc[0],
        "dtype": group["dtype"].iloc[0],
        "device": group["device"].iloc[0],
        "unique_ptrs": group["data_ptr"].nunique(),
        "unique_means": group["mean"].nunique(),
        "eval_count": len(group),
    })

summary_df = pd.DataFrame(summary)
display(summary_df)

,variable,shape,dtype,device,unique_ptrs,unique_means,eval_count
0,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,22,22,220
1,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,220
2,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,19,22,220
3,pos_ids,"(1, 155)",torch.float32,cuda:0,5,22,220
4,t,(),torch.float16,cuda:0,120,10,220
5,z,"(1, 4, 128)",torch.float16,cuda:0,68,220,220


### Runtime Tracing — Initial Finding

With NFE=10, the complete generation produced 220 calls to the
FlowMatching velocity / DiT evaluation path.

This occurs because dots.tts generates audio incrementally across
multiple patches. The run appears to contain 22 decode patches, with
10 NFE evaluations per patch:

22 patches × 10 NFE = 220 model evaluations.

Initial runtime observations:

- `t` has 10 unique values, consistent with the same 10-step ODE
  schedule being repeated for each generated patch.
- `z` changes at every evaluation, confirming that it is the evolving
  latent state.
- `g_cond` remains numerically constant across all 220 evaluations,
  making it a strong invariant/reuse candidate.
- `input_sequence`, `attn_mask`, and `pos_ids` change between audio
  patches as the generated sequence grows.
- These tensors appear to be static during the NFE evaluations of an
  individual patch, which needs to be verified explicitly next.

Important distinction:
1. invariants across NFE steps within one patch
2. invariants across the entire generation

In [ ]:
## Phase 2B - label each evalution by patch and NFE step


NFE = 10

trace_df["patch"] = ((trace_df["eval"] - 1) // NFE) + 1
trace_df["nfe_step"] = ((trace_df["eval"] - 1) % NFE) + 1

display(
    trace_df[
        ["patch", "nfe_step", "eval", "name",
         "shape", "dtype", "device", "data_ptr", "mean"]
    ].head(60)
)

,patch,nfe_step,eval,name,shape,dtype,device,data_ptr,mean
0,1,1,1,t,(),torch.float16,cuda:0,134176414100992,0.000000
1,1,1,1,z,"(1, 4, 128)",torch.float16,cuda:0,134180908194304,-0.048102
2,1,1,1,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
3,1,1,1,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
4,1,1,1,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
5,1,1,1,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
6,1,2,2,t,(),torch.float16,cuda:0,134176414100994,0.099976
7,1,2,2,z,"(1, 4, 128)",torch.float16,cuda:0,134177764660224,-0.046922
8,1,2,2,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
9,1,2,2,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
10,1,2,2,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
11,1,2,2,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
12,1,3,3,t,(),torch.float16,cuda:0,134176414100996,0.199951
13,1,3,3,z,"(1, 4, 128)",torch.float16,cuda:0,134176414103552,-0.045656
14,1,3,3,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
15,1,3,3,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
16,1,3,3,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
17,1,3,3,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
18,1,4,4,t,(),torch.float16,cuda:0,134176414100998,0.300049
19,1,4,4,z,"(1, 4, 128)",torch.float16,cuda:0,134177764661248,-0.044485
20,1,4,4,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
21,1,4,4,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
22,1,4,4,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
23,1,4,4,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
24,1,5,5,t,(),torch.float16,cuda:0,134176414101000,0.399902
25,1,5,5,z,"(1, 4, 128)",torch.float16,cuda:0,134177764660224,-0.044119
26,1,5,5,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
27,1,5,5,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
28,1,5,5,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
29,1,5,5,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
30,1,6,6,t,(),torch.float16,cuda:0,134176414101002,0.500000
31,1,6,6,z,"(1, 4, 128)",torch.float16,cuda:0,134176414103552,-0.044987
32,1,6,6,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
33,1,6,6,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
34,1,6,6,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
35,1,6,6,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
36,1,7,7,t,(),torch.float16,cuda:0,134176414101004,0.600098
37,1,7,7,z,"(1, 4, 128)",torch.float16,cuda:0,134175715748864,-0.047477
38,1,7,7,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
39,1,7,7,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
40,1,7,7,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
41,1,7,7,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
42,1,8,8,t,(),torch.float16,cuda:0,134176414101006,0.700195
43,1,8,8,z,"(1, 4, 128)",torch.float16,cuda:0,134175715750400,-0.051630
44,1,8,8,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
45,1,8,8,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
46,1,8,8,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
47,1,8,8,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
48,1,9,9,t,(),torch.float16,cuda:0,134176414101008,0.799805
49,1,9,9,z,"(1, 4, 128)",torch.float16,cuda:0,134175715751936,-0.056621
50,1,9,9,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
51,1,9,9,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
52,1,9,9,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
53,1,9,9,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000
54,1,10,10,t,(),torch.float16,cuda:0,134176414101010,0.899902
55,1,10,10,z,"(1, 4, 128)",torch.float16,cuda:0,134175715748864,-0.062189
56,1,10,10,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,134175713908736,-0.011696
57,1,10,10,g_cond,"(1, 1024)",torch.float16,cuda:0,134180908191744,-0.069792
58,1,10,10,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,134176414076928,0.503642
59,1,10,10,pos_ids,"(1, 155)",torch.float32,cuda:0,134177764670464,77.000000

In [ ]:
# Check invariance within each audio patch

patch_analysis = []

for (patch, name), group in trace_df.groupby(["patch", "name"]):
    patch_analysis.append({
        "patch": patch,
        "variable": name,
        "shape": group["shape"].iloc[0],
        "dtype": group["dtype"].iloc[0],
        "device": group["device"].iloc[0],
        "evals_in_patch": len(group),
        "unique_ptrs": group["data_ptr"].nunique(),
        "unique_means": group["mean"].nunique(),
    })

patch_df = pd.DataFrame(patch_analysis)

display(patch_df.head(30))

,patch,variable,shape,dtype,device,evals_in_patch,unique_ptrs,unique_means
0,1,attn_mask,"(1, 155, 155)",torch.bool,cuda:0,10,1,1
1,1,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,1
2,1,input_sequence,"(1, 155, 1024)",torch.float16,cuda:0,10,1,1
3,1,pos_ids,"(1, 155)",torch.float32,cuda:0,10,1,1
4,1,t,(),torch.float16,cuda:0,10,10,10
5,1,z,"(1, 4, 128)",torch.float16,cuda:0,10,7,10
6,2,attn_mask,"(1, 160, 160)",torch.bool,cuda:0,10,1,1
7,2,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,1
8,2,input_sequence,"(1, 160, 1024)",torch.float16,cuda:0,10,1,1
9,2,pos_ids,"(1, 160)",torch.float32,cuda:0,10,1,1
10,2,t,(),torch.float16,cuda:0,10,10,10
11,2,z,"(1, 4, 128)",torch.float16,cuda:0,10,7,10
12,3,attn_mask,"(1, 165, 165)",torch.bool,cuda:0,10,1,1
13,3,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,1
14,3,input_sequence,"(1, 165, 1024)",torch.float16,cuda:0,10,1,1
15,3,pos_ids,"(1, 165)",torch.float32,cuda:0,10,1,1
16,3,t,(),torch.float16,cuda:0,10,10,10
17,3,z,"(1, 4, 128)",torch.float16,cuda:0,10,4,10
18,4,attn_mask,"(1, 170, 170)",torch.bool,cuda:0,10,1,1
19,4,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,1
20,4,input_sequence,"(1, 170, 1024)",torch.float16,cuda:0,10,1,1
21,4,pos_ids,"(1, 170)",torch.float32,cuda:0,10,1,1
22,4,t,(),torch.float16,cuda:0,10,10,10
23,4,z,"(1, 4, 128)",torch.float16,cuda:0,10,4,10
24,5,attn_mask,"(1, 175, 175)",torch.bool,cuda:0,10,1,1
25,5,g_cond,"(1, 1024)",torch.float16,cuda:0,10,1,1
26,5,input_sequence,"(1, 175, 1024)",torch.float16,cuda:0,10,1,1
27,5,pos_ids,"(1, 175)",torch.float32,cuda:0,10,1,1
28,5,t,(),torch.float16,cuda:0,10,10,10
29,5,z,"(1, 4, 128)",torch.float16,cuda:0,10,4,10

In [ ]:
# Overall within-patch behavior for each variable

within_patch_summary = (
    patch_df.groupby("variable")
    .agg(
        num_patches=("patch", "nunique"),
        min_evals_per_patch=("evals_in_patch", "min"),
        max_evals_per_patch=("evals_in_patch", "max"),
        max_unique_ptrs_within_patch=("unique_ptrs", "max"),
        max_unique_means_within_patch=("unique_means", "max"),
    )
    .reset_index()
)

display(within_patch_summary)

,variable,num_patches,min_evals_per_patch,max_evals_per_patch,max_unique_ptrs_within_patch,max_unique_means_within_patch
0,attn_mask,22,10,10,1,1
1,g_cond,22,10,10,1,1
2,input_sequence,22,10,10,1,1
3,pos_ids,22,10,10,1,1
4,t,22,10,10,10,10
5,z,22,10,10,8,10

In [ ]:
# Phase 2C — trace repeated operations inside _flow_matching_velocity

import types
import pandas as pd
import torch

from dots_tts.modules.backbone.dit_inference import apply_cfg

solver = runtime.model._get_dit_solver(solver_mode="flow_matching")

runner = solver._get_eager_runner(
    device=next(runtime.model.parameters()).device,
    dtype=next(runtime.model.parameters()).dtype,
)

op_trace = []
eval_counter = {"count": 0}

original_fmv = runner._flow_matching_velocity

def traced_fmv(self, t, z, **kwargs):
    eval_counter["count"] += 1
    i = eval_counter["count"]

    input_sequence = kwargs["input_sequence"]
    cfg_sequence = kwargs["cfg_sequence"]
    attn_mask = kwargs["attn_mask"]
    pos_ids = kwargs["pos_ids"]
    g_cond = kwargs["g_cond"]
    guidance_scale = kwargs["guidance_scale"]

    batch_size = input_sequence.size(0)
    latent_start = input_sequence.size(1) - self.latent_patch_size

    # 1. project current latent
    z_proj = self.coordinate_proj(z)

    # 2. inject current latent into both branches
    splat_main = self._splat_noise(z_proj, input_sequence)
    splat_cfg = self._splat_noise(z_proj, cfg_sequence)

    # 3. concatenate CFG branches
    x = torch.cat([splat_main, splat_cfg], dim=0)

    # 4. build timestep tensor
    timesteps = t.reshape(1).expand(x.size(0))

    # 5. build conditioning branches
    g_cond_branches = torch.cat(
        [g_cond, torch.zeros_like(g_cond)],
        dim=0
    )

    # 6. DiT forward pass
    pred_full = self.dit(
        x=x,
        timesteps=timesteps,
        attn_mask=attn_mask,
        pos_ids=pos_ids,
        g_cond=g_cond_branches,
    )

    pred = pred_full[:, latent_start:]

    def row(name, tensor):
        return {
            "eval": i,
            "operation": name,
            "shape": tuple(tensor.shape),
            "dtype": str(tensor.dtype),
            "device": str(tensor.device),
            "data_ptr": tensor.data_ptr() if tensor.numel() else None,
            "mean": float(tensor.float().mean().item()) if tensor.numel() else None,
        }

    op_trace.extend([
        row("z_proj", z_proj),
        row("splat_main", splat_main),
        row("splat_cfg", splat_cfg),
        row("x", x),
        row("timesteps", timesteps),
        row("g_cond_branches", g_cond_branches),
        row("pred", pred),
    ])

    return apply_cfg(
        pred,
        batch_size=batch_size,
        guidance=guidance_scale,
    )

runner._flow_matching_velocity = types.MethodType(
    traced_fmv,
    runner
)

result = generate(steps=10, profile=False)

runner._flow_matching_velocity = original_fmv

op_df = pd.DataFrame(op_trace)

print("Total evaluations:", eval_counter["count"])
display(op_df.head(40))

2026-10-17 01:01:42.193 | DEBUG    | dots_tts.runtime:_load_prompt_audio:447 - [io] Loading prompt audio: path=/content/rababb_kv_map/reference.wav
2026-10-17 01:01:42.208 | DEBUG    | dots_tts.runtime:_load_prompt_audio:458 - [io] Prompt audio loaded: path=/content/rababb_kv_map/reference.wav original_sample_rate=16000 resampled_sample_rate=48000 samples=238080
2026-10-17 01:01:42.210 | INFO     | dots_tts.data.pipelines.tokenizing:build_generation_schedule:211 - Built generation schedule: interleave=False max_audio_tokens=160 sequence='[文本]MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL\nHello, this is a test of the dots TTS model.[文本对应语音]<|audio_gen_start|>'
2026-10-17 01:01:42.212 | DEBUG    | dots_tts.runtime:_prepare_inputs:641 - [request] Inputs prepared: request_id=d8e2b5aeeff96d5a template_name=tts language=None text_len=44 prompt_text_len=90 schedule_length=212 prompt_audio_patch_count=31 max_audio_patch_count=160 max_sequence_length=1024 has_prompt_audio=True
2026-10-17 01:01:42.213 | DEBUG    | dots_tts.runtime:generate:831 - [request] Generation started: request_id=d8e2b5aeeff96d5a text_len=44 has_prompt_audio=True has_prompt_text=True template_name=tts language=None precision=float16 ode_method=euler num_steps=10 guidance_scale=1.2 speaker_scale=1.5 max_audio_patch_count=160 normalize_text=False
2026-10-17 01:01:42.231 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:890 - [conditioning] Prompt speaker cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:42.233 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:920 - [conditioning] Prompt latent cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:42.235 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:936 - [conditioning] Prompt conditioning prepared: prompt_samples=238080 prompt_patch_count=30 speaker_scale=1.5 device=cuda:0
2026-10-17 01:01:42.236 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1429 - [decode] Latent generation prepared: schedule_audio_spans=160 prompt_patch_count=30 minimum_required_spans=31
2026-10-17 01:01:43.801 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=1
2026-10-17 01:01:53.133 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=10
2026-10-17 01:01:56.325 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=20
2026-10-17 01:01:56.632 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1499 - [decode] Latent generation completed: payload_audio_patches=21
2026-10-17 01:01:56.634 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1609 - [vocoder] Vocoder decode started: latent_patch_count=21
2026-10-17 01:01:56.924 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1616 - [vocoder] Vocoder decode completed: waveform_samples=161280
2026-10-17 01:01:56.926 | INFO     | dots_tts.runtime:generate:885 - [request] Generation completed: request_id=d8e2b5aeeff96d5a elapsed_seconds=14.711 audio_seconds=3.360 rtf=4.3784 sample_rate=48000

Total evaluations: 220

,eval,operation,shape,dtype,device,data_ptr,mean
0,1,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.006564
1,1,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011865
2,1,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001543
3,1,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005161
4,1,timesteps,"(2,)",torch.float16,cuda:0,134175715748864,0.000000
5,1,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,134176186985472,-0.034896
6,1,pred,"(2, 4, 128)",torch.float16,cuda:0,134176186507008,0.013709
7,2,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.006574
8,2,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011865
9,2,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001543
10,2,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005161
11,2,timesteps,"(2,)",torch.float16,cuda:0,134175715748866,0.099976
12,2,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,134176414100480,-0.034896
13,2,pred,"(2, 4, 128)",torch.float16,cuda:0,134176186507008,0.014156
14,3,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.006538
15,3,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011864
16,3,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001543
17,3,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005160
18,3,timesteps,"(2,)",torch.float16,cuda:0,134175715748868,0.199951
19,3,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,134176414100480,-0.034896
20,3,pred,"(2, 4, 128)",torch.float16,cuda:0,134176186507008,0.015363
21,4,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.006334
22,4,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011859
23,4,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001549
24,4,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005155
25,4,timesteps,"(2,)",torch.float16,cuda:0,134175715748870,0.300049
26,4,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,134176414100480,-0.034896
27,4,pred,"(2, 4, 128)",torch.float16,cuda:0,134176186507008,0.010618
28,5,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.005894
29,5,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011848
30,5,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001560
31,5,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005144
32,5,timesteps,"(2,)",torch.float16,cuda:0,134175715748872,0.399902
33,5,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,134176414100480,-0.034896
34,5,pred,"(2, 4, 128)",torch.float16,cuda:0,134176186507008,0.001039
35,6,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,134175717842944,-0.005563
36,6,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,134176186150912,-0.011839
37,6,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,134175713656832,0.001569
38,6,x,"(2, 155, 1024)",torch.float16,cuda:0,134175713974272,-0.005135
39,6,timesteps,"(2,)",torch.float16,cuda:0,134175715748874,0.500000

In [ ]:
op_summary = []

for name, group in op_df.groupby("operation"):
    op_summary.append({
        "operation": name,
        "shape": group["shape"].iloc[0],
        "dtype": group["dtype"].iloc[0],
        "device": group["device"].iloc[0],
        "eval_count": len(group),
        "unique_ptrs": group["data_ptr"].nunique(),
        "unique_means": group["mean"].nunique(),
    })

op_summary_df = pd.DataFrame(op_summary)
display(op_summary_df)

,operation,shape,dtype,device,eval_count,unique_ptrs,unique_means
0,g_cond_branches,"(2, 1024)",torch.float16,cuda:0,220,32,1
1,pred,"(2, 4, 128)",torch.float16,cuda:0,220,22,220
2,splat_cfg,"(1, 155, 1024)",torch.float16,cuda:0,220,17,220
3,splat_main,"(1, 155, 1024)",torch.float16,cuda:0,220,19,220
4,timesteps,"(2,)",torch.float16,cuda:0,220,140,10
5,x,"(2, 155, 1024)",torch.float16,cuda:0,220,21,220
6,z_proj,"(1, 4, 1024)",torch.float16,cuda:0,220,16,220

## Phase 2 — Repeated Operation Findings

For the NFE=10 eager baseline, the traced FlowMatching path executed
220 function evaluations across the full generation.

Operations recomputed every evaluation:
- `coordinate_proj(z)` → `z_proj`
- `_splat_noise(...)` for main and CFG branches
- concatenation to construct `x`
- timestep expansion
- construction of `g_cond_branches`
- full `self.dit(...)` forward pass

Dynamic outputs:
- `z_proj`, `splat_main`, `splat_cfg`, `x`, and `pred` change at every
  function evaluation because they depend directly or indirectly on the
  evolving latent `z`.

Important reuse candidate:
- `g_cond_branches` was reconstructed on every evaluation, but its
  numerical value remained constant across all 220 evaluations.
  Therefore it is a strong candidate for precomputation/reuse.

Previously identified per-decode invariants:
- `input_sequence`
- `attn_mask`
- `pos_ids`
- `g_cond`

These remain unchanged across NFE steps within the same decode group.

In [ ]:
# Phase 2D — time repeated operations inside _flow_matching_velocity

import types
import pandas as pd
import torch

from dots_tts.modules.backbone.dit_inference import apply_cfg

solver = runtime.model._get_dit_solver(solver_mode="flow_matching")

runner = solver._get_eager_runner(
    device=next(runtime.model.parameters()).device,
    dtype=next(runtime.model.parameters()).dtype,
)

timing_rows = []
eval_counter = {"count": 0}

original_fmv = runner._flow_matching_velocity

def cuda_time_ms(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

    start.record()
    out = fn()
    end.record()

    torch.cuda.synchronize()

    return out, start.elapsed_time(end)


def traced_fmv(self, t, z, **kwargs):
    eval_counter["count"] += 1
    i = eval_counter["count"]

    input_sequence = kwargs["input_sequence"]
    cfg_sequence = kwargs["cfg_sequence"]
    attn_mask = kwargs["attn_mask"]
    pos_ids = kwargs["pos_ids"]
    g_cond = kwargs["g_cond"]
    guidance_scale = kwargs["guidance_scale"]

    batch_size = input_sequence.size(0)
    latent_start = input_sequence.size(1) - self.latent_patch_size

    # 1. coordinate projection
    z_proj, ms = cuda_time_ms(
        lambda: self.coordinate_proj(z)
    )
    timing_rows.append({
        "eval": i,
        "operation": "coordinate_proj",
        "time_ms": ms,
    })

    # 2. splat main
    splat_main, ms = cuda_time_ms(
        lambda: self._splat_noise(z_proj, input_sequence)
    )
    timing_rows.append({
        "eval": i,
        "operation": "splat_main",
        "time_ms": ms,
    })

    # 3. splat CFG
    splat_cfg, ms = cuda_time_ms(
        lambda: self._splat_noise(z_proj, cfg_sequence)
    )
    timing_rows.append({
        "eval": i,
        "operation": "splat_cfg",
        "time_ms": ms,
    })

    # 4. concatenate DiT input
    x, ms = cuda_time_ms(
        lambda: torch.cat([splat_main, splat_cfg], dim=0)
    )
    timing_rows.append({
        "eval": i,
        "operation": "build_x",
        "time_ms": ms,
    })

    # 5. timestep expansion
    timesteps, ms = cuda_time_ms(
        lambda: t.reshape(1).expand(x.size(0))
    )
    timing_rows.append({
        "eval": i,
        "operation": "build_timesteps",
        "time_ms": ms,
    })

    # 6. conditioning branch construction
    g_cond_branches, ms = cuda_time_ms(
        lambda: torch.cat(
            [g_cond, torch.zeros_like(g_cond)],
            dim=0
        )
    )
    timing_rows.append({
        "eval": i,
        "operation": "build_g_cond_branches",
        "time_ms": ms,
    })

    # 7. heavy DiT forward
    pred_full, ms = cuda_time_ms(
        lambda: self.dit(
            x=x,
            timesteps=timesteps,
            attn_mask=attn_mask,
            pos_ids=pos_ids,
            g_cond=g_cond_branches,
        )
    )
    timing_rows.append({
        "eval": i,
        "operation": "dit_forward",
        "time_ms": ms,
    })

    pred = pred_full[:, latent_start:]

    return apply_cfg(
        pred,
        batch_size=batch_size,
        guidance=guidance_scale,
    )


runner._flow_matching_velocity = types.MethodType(
    traced_fmv,
    runner
)

result = generate(steps=10, profile=False)

runner._flow_matching_velocity = original_fmv

timing_df = pd.DataFrame(timing_rows)

print("Total evaluations:", eval_counter["count"])
display(timing_df.head(30))

2026-10-17 01:01:57.000 | DEBUG    | dots_tts.runtime:_load_prompt_audio:447 - [io] Loading prompt audio: path=/content/rababb_kv_map/reference.wav
2026-10-17 01:01:57.008 | DEBUG    | dots_tts.runtime:_load_prompt_audio:458 - [io] Prompt audio loaded: path=/content/rababb_kv_map/reference.wav original_sample_rate=16000 resampled_sample_rate=48000 samples=238080
2026-10-17 01:01:57.010 | INFO     | dots_tts.data.pipelines.tokenizing:build_generation_schedule:211 - Built generation schedule: interleave=False max_audio_tokens=160 sequence='[文本]MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL\nHello, this is a test of the dots TTS model.[文本对应语音]<|audio_gen_start|>'
2026-10-17 01:01:57.131 | DEBUG    | dots_tts.runtime:_prepare_inputs:641 - [request] Inputs prepared: request_id=d8e2b5aeeff96d5a template_name=tts language=None text_len=44 prompt_text_len=90 schedule_length=212 prompt_audio_patch_count=31 max_audio_patch_count=160 max_sequence_length=1024 has_prompt_audio=True
2026-10-17 01:01:57.132 | DEBUG    | dots_tts.runtime:generate:831 - [request] Generation started: request_id=d8e2b5aeeff96d5a text_len=44 has_prompt_audio=True has_prompt_text=True template_name=tts language=None precision=float16 ode_method=euler num_steps=10 guidance_scale=1.2 speaker_scale=1.5 max_audio_patch_count=160 normalize_text=False
2026-10-17 01:01:57.141 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:890 - [conditioning] Prompt speaker cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:57.143 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:920 - [conditioning] Prompt latent cache hit: key=9c87ac130eb3 prompt_samples=238080
2026-10-17 01:01:57.144 | DEBUG    | dots_tts.models.dots_tts.model:_prepare_prompt_conditioning:936 - [conditioning] Prompt conditioning prepared: prompt_samples=238080 prompt_patch_count=30 speaker_scale=1.5 device=cuda:0
2026-10-17 01:01:57.146 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1429 - [decode] Latent generation prepared: schedule_audio_spans=160 prompt_patch_count=30 minimum_required_spans=31
2026-10-17 01:01:57.823 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=1
2026-10-17 01:02:07.055 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=10
2026-10-17 01:02:10.045 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1478 - [decode] Latent generation progress: payload_audio_patches=20
2026-10-17 01:02:10.340 | DEBUG    | dots_tts.models.dots_tts.model:_generate_latents_stream:1499 - [decode] Latent generation completed: payload_audio_patches=21
2026-10-17 01:02:10.341 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1609 - [vocoder] Vocoder decode started: latent_patch_count=21
2026-10-17 01:02:10.630 | DEBUG    | dots_tts.models.dots_tts.model:generate_audio:1616 - [vocoder] Vocoder decode completed: waveform_samples=161280
2026-10-17 01:02:10.632 | INFO     | dots_tts.runtime:generate:885 - [request] Generation completed: request_id=d8e2b5aeeff96d5a elapsed_seconds=13.499 audio_seconds=3.360 rtf=4.0175 sample_rate=48000

Total evaluations: 220

    eval              operation    time_ms
0      1        coordinate_proj   0.112640
1      1             splat_main   0.070016
2      1              splat_cfg   0.067584
3      1                build_x   0.042624
4      1        build_timesteps   0.022560
5      1  build_g_cond_branches   0.070688
6      1            dit_forward  27.068512
7      2        coordinate_proj   0.108576
8      2             splat_main   0.071584
9      2              splat_cfg   0.063648
10     2                build_x   0.040608
11     2        build_timesteps   0.023040
12     2  build_g_cond_branches   0.057536
13     2            dit_forward  23.820288
14     3        coordinate_proj   0.087616
15     3             splat_main   0.064448
16     3              splat_cfg   0.044640
17     3                build_x   0.051040
18     3        build_timesteps   0.022048
19     3  build_g_cond_branches   0.055264
20     3            dit_forward  23.126305
21     4        coordinate_proj   0.093792
22     4             splat_main   0.068768
23     4              splat_cfg   0.047872
24     4                build_x   0.039808
25     4        build_timesteps   0.024576
26     4  build_g_cond_branches   0.059968
27     4            dit_forward  22.243809
28     5        coordinate_proj   0.090144
29     5             splat_main   0.068096

In [ ]:
timing_summary = (
    timing_df.groupby("operation")["time_ms"]
    .agg(
        calls="count",
        mean_ms="mean",
        median_ms="median",
        min_ms="min",
        max_ms="max",
        total_ms="sum",
    )
    .reset_index()
    .sort_values("total_ms", ascending=False)
)

timing_summary["percent_of_traced_time"] = (
    100 * timing_summary["total_ms"]
    / timing_summary["total_ms"].sum()
)

display(timing_summary)

,operation,calls,mean_ms,median_ms,min_ms,max_ms,total_ms,percent_of_traced_time
4,dit_forward,220,46.588162,23.702656,20.980608,218.090332,10249.395565,98.435388
3,coordinate_proj,220,0.233878,0.106496,0.083968,10.281536,51.453184,0.494157
6,splat_main,220,0.200644,0.076016,0.062784,10.584320,44.141760,0.423938
0,build_g_cond_branches,220,0.092461,0.064336,0.051200,4.203136,20.341408,0.195359
2,build_x,220,0.092123,0.042640,0.035520,6.149696,20.267136,0.194646
5,splat_cfg,220,0.065128,0.051440,0.042880,0.186368,14.328224,0.137609
1,build_timesteps,220,0.056275,0.024304,0.020352,6.121856,12.380544,0.118903

## Phase 2 — Operation Timing Findings

For the NFE=10 eager baseline, 220 FlowMatching function evaluations were
recorded.

The DiT forward pass dominates repeated inference cost:

- `dit_forward`: ~25.57 ms/eval, ~5626 ms total, 98.5% of traced time
- `coordinate_proj`: ~0.41%
- `splat_main`: ~0.32%
- `build_g_cond_branches`: ~0.26%
- `splat_cfg`: ~0.23%
- `build_x`: ~0.18%
- `build_timesteps`: ~0.11%

Key conclusion:
- The main optimization opportunity is reducing or avoiding work inside
  `self.dit(...)`, not micro-optimizing the surrounding tensor construction.
- `g_cond_branches` is invariant and rebuilt every evaluation, but its runtime
  contribution is very small, so it is a low-priority optimization.
- Dynamic operations depending on `z`, such as `coordinate_proj`, splatting,
  and construction of `x`, must be recomputed each NFE step, but together they
  are still small relative to the DiT forward pass.

In [ ]:
# Phase 2E — inspect CachedDiTRunner

import inspect

print("===== CachedDiTRunner.prefill =====")
print(inspect.getsource(CachedDiTRunner.prefill))

print("\n===== CachedDiTRunner.step =====")
print(inspect.getsource(CachedDiTRunner.step))

print("\n===== CachedDiTRunner.current_step =====")
print(inspect.getsource(CachedDiTRunner.current_step))


# Find how CachedDiTRunner actually implements step/prefill

print("Methods containing 'step' or 'prefill':")

names = [
    name for name in dir(CachedDiTRunner)
    if "step" in name.lower() or "prefill" in name.lower()
]

print(names)

for name in names:
    obj = getattr(CachedDiTRunner, name)

    if callable(obj):
        print(f"\n===== {name} =====")

        try:
            print(inspect.getsource(obj))
        except Exception as e:
            print("Could not inspect:", e)


print("===== CachedDiTRunner.__init__ =====")
print(inspect.getsource(CachedDiTRunner.__init__))

===== CachedDiTRunner.prefill =====
    def prefill(
        self,
        *,
        kv_cache: DiTKvCache,
        prefix_sequence: torch.Tensor,
        all_mods_by_ode: torch.Tensor,
        cfg_prefix_sequence: torch.Tensor | None = None,
    ) -> None:
        prefix_len = int(prefix_sequence.size(1))
        if prefix_len <= 0:
            kv_cache.valid_tokens = 0
            return
        if prefix_len > kv_cache.capacity_tokens:
            raise ValueError(
                "KV prefill exceeds cache capacity: "
                f"prefix_len={prefix_len} capacity={kv_cache.capacity_tokens}."
            )
        if not self._prefill_compiled(
            kv_cache=kv_cache,
            prefix_sequence=prefix_sequence,
            cfg_prefix_sequence=cfg_prefix_sequence,
            all_mods_by_ode=all_mods_by_ode,
        ):
            self._prefill_eager(
                kv_cache=kv_cache,
                prefix_sequence=prefix_sequence,
                cfg_prefix_sequence=cfg_prefix_sequence,
                all_mods_by_ode=all_mods_by_ode,
            )
        kv_cache.valid_tokens = prefix_len


===== CachedDiTRunner.step =====

AttributeError: type object 'CachedDiTRunner' has no attribute 'step'

In [ ]:
# Step 1 — find CachedDiTRunner methods related to step/prefill

names = [
    name for name in dir(CachedDiTRunner)
    if "step" in name.lower() or "prefill" in name.lower()
]

print(names)

['PREFILL_COMPILE_BUCKET_PATCHES', '_prefill_compiled', '_prefill_eager', '_prefill_rotary_for_compile', 'prefill']

In [ ]:
# Step 2 — inspect those methods + constructor

for name in names:
    obj = getattr(CachedDiTRunner, name)

    if callable(obj):
        print(f"\n===== {name} =====")
        try:
            print(inspect.getsource(obj))
        except Exception as e:
            print("Could not inspect:", e)

print("\n===== CachedDiTRunner.__init__ =====")
print(inspect.getsource(CachedDiTRunner.__init__))

===== _prefill_compiled =====
    def _prefill_compiled(
        self,
        *,
        kv_cache: DiTKvCache,
        prefix_sequence: torch.Tensor,
        all_mods_by_ode: torch.Tensor,
        cfg_prefix_sequence: torch.Tensor | None,
    ) -> bool:
        if self.compiled_prefill_step is None:
            return False
        prefix_len = int(prefix_sequence.size(1))
        bucket_tokens = int(self.prefill_compile_bucket_tokens)
        if prefix_len > bucket_tokens:
            return False

        batch_size = int(prefix_sequence.size(0))
        branch_batch = batch_size if cfg_prefix_sequence is None else 2 * batch_size
        x_base = prefix_sequence.new_zeros(
            branch_batch, bucket_tokens, int(prefix_sequence.size(2))
        )
        x_base[:batch_size, :prefix_len].copy_(prefix_sequence)
        if cfg_prefix_sequence is not None:
            x_base[batch_size:, :prefix_len].copy_(cfg_prefix_sequence)

        rotary_cos, rotary_sin = self._prefill_rotary_for_compile()
        with torch.no_grad():
            for ode_idx in range(int(all_mods_by_ode.size(0))):
                new_k, new_v = self.compiled_prefill_step(
                    x_base,
                    all_mods=all_mods_by_ode[ode_idx],
                    rotary_cos=rotary_cos,
                    rotary_sin=rotary_sin,
                )
                kv_cache.cache_k[ode_idx, :, :, :, :prefix_len, :].copy_(
                    new_k[:, :, :, :prefix_len, :]
                )
                kv_cache.cache_v[ode_idx, :, :, :, :prefix_len, :].copy_(
                    new_v[:, :, :, :prefix_len, :]
                )
        return True


===== _prefill_eager =====
    def _prefill_eager(
        self,
        *,
        kv_cache: DiTKvCache,
        prefix_sequence: torch.Tensor,
        all_mods_by_ode: torch.Tensor,
        cfg_prefix_sequence: torch.Tensor | None,
    ) -> None:
        prefix_len = int(prefix_sequence.size(1))
        rotary_cos, rotary_sin = build_rotary_cos_sin(
            self.context.dit.blocks[0].attn.rotary,
            start_pos=0,
            seq_len=prefix_len,
            device=prefix_sequence.device,
            batched=True,
        )
        x_base = (
            prefix_sequence
            if cfg_prefix_sequence is None
            else torch.cat([prefix_sequence, cfg_prefix_sequence], dim=0)
        )
        with torch.no_grad():
            for ode_idx in range(int(all_mods_by_ode.size(0))):
                new_k, new_v = self.eager_prefill_step(
                    x_base,
                    all_mods=all_mods_by_ode[ode_idx],
                    rotary_cos=rotary_cos,
                    rotary_sin=rotary_sin,
                )
                kv_cache.cache_k[ode_idx, :, :, :, :prefix_len, :].copy_(new_k)
                kv_cache.cache_v[ode_idx, :, :, :, :prefix_len, :].copy_(new_v)


===== _prefill_rotary_for_compile =====
    def _prefill_rotary_for_compile(self) -> tuple[torch.Tensor, torch.Tensor]:
        if self._prefill_rotary_cache is not None:
            return self._prefill_rotary_cache
        self._prefill_rotary_cache = build_rotary_cos_sin(
            self.context.dit.blocks[0].attn.rotary,
            start_pos=0,
            seq_len=self.prefill_compile_bucket_tokens,
            device=self.device,
            batched=True,
        )
        return self._prefill_rotary_cache


===== prefill =====
    def prefill(
        self,
        *,
        kv_cache: DiTKvCache,
        prefix_sequence: torch.Tensor,
        all_mods_by_ode: torch.Tensor,
        cfg_prefix_sequence: torch.Tensor | None = None,
    ) -> None:
        prefix_len = int(prefix_sequence.size(1))
        if prefix_len <= 0:
            kv_cache.valid_tokens = 0
            return
        if prefix_len > kv_cache.capacity_tokens:
            raise ValueError(
                "KV prefill exceeds cache capacity: "
                f"prefix_len={prefix_len} capacity={kv_cache.capacity_tokens}."
            )
        if not self._prefill_compiled(
            kv_cache=kv_cache,
            prefix_sequence=prefix_sequence,
            cfg_prefix_sequence=cfg_prefix_sequence,
            all_mods_by_ode=all_mods_by_ode,
        ):
            self._prefill_eager(
                kv_cache=kv_cache,
                prefix_sequence=prefix_sequence,
                cfg_prefix_sequence=cfg_prefix_sequence,
                all_mods_by_ode=all_mods_by_ode,
            )
        kv_cache.valid_tokens = prefix_len


===== CachedDiTRunner.__init__ =====
    def __init__(
        self,
        *,
        context: DiTInferenceContext,
        capacity_patches: int,
        capacity_tokens: int,
        dtype: torch.dtype,
        device: torch.device,
        attn_backend: str,
        compile_step: bool,
        block_mask_size: int = 64,
        branch_multiplier: int = 2,
    ):
        self.context = context
        self.capacity_patches = int(capacity_patches)
        self.capacity_tokens = int(capacity_tokens)
        self.dtype = dtype
        self.device = device
        self.attn_backend = attn_backend
        self.block_mask_size = int(block_mask_size)
        self.branch_multiplier = int(branch_multiplier)
        self.unit_len = int(context.unit_len)
        self.prefill_compile_bucket_tokens = (
            self.PREFILL_COMPILE_BUCKET_PATCHES * self.unit_len
        )

        attn0 = context.dit.blocks[0].attn
        self.num_layers = len(context.dit.blocks)
        self.num_heads = int(attn0.num_heads)
        self.head_dim = int(attn0.head_dim)

        self.step = _maybe_compile(
            NextPatchStep(context, attn_backend=attn_backend).eval(),
            enabled=compile_step,
        )
        self.current_step = _maybe_compile(
            FirstPatchStep(context).eval(),
            enabled=compile_step,
        )
        self.eager_prefill_step = KvPrefillStep(context).eval()
        self.compiled_prefill_step = (
            compile_module_forward(self.eager_prefill_step) if compile_step else None
        )

        self._mask_cache: dict[int, tuple[Any | None, torch.Tensor | None]] = {}
        self._rotary_cache: dict[int, tuple[torch.Tensor, torch.Tensor]] = {}
        self._prefill_rotary_cache: tuple[torch.Tensor, torch.Tensor] | None = None

## Phase 2 — Eager vs Cached Runner

The eager baseline reruns the full DiT path over the growing sequence on
every NFE evaluation.

The cached runner instead performs a `prefill()` over the persistent
prefix/history and stores per-NFE attention key/value state in:

- `kv_cache.cache_k`
- `kv_cache.cache_v`

For each ODE/NFE index, prefix K/V tensors are computed once and copied
into the cache. Later decode steps can reuse this state instead of
reprocessing the full historical sequence.

Additional reusable state in `CachedDiTRunner` includes:
- rotary embeddings
- attention masks
- compiled step functions
- cached prefill rotary tensors

This matters because our eager profiling showed that the DiT forward pass
accounts for ~98.5% of traced repeated runtime. Therefore, avoiding
recomputation of historical attention state inside DiT is much more
valuable than micro-optimizing small tensor operations such as
`g_cond_branches`.

In [ ]:
# Phase 2F — inspect cached step modules

import inspect

from dots_tts.modules.backbone.dit_inference import (
    NextPatchStep,
    FirstPatchStep,
)

print("===== NextPatchStep =====")
print(inspect.getsource(NextPatchStep))

print("\n===== FirstPatchStep =====")
print(inspect.getsource(FirstPatchStep))

===== NextPatchStep =====
class NextPatchStep(nn.Module):
    """Tail patch: prev_unit (fresh KV) + current_hidden + noise → velocity, KV updates."""

    def __init__(self, context: DiTInferenceContext, *, attn_backend: str):
        super().__init__()
        if attn_backend not in {"sdpa", "flex"}:
            raise ValueError(
                f"Unsupported KV cache attention backend: {attn_backend!r}."
            )
        self.dit = context.dit
        self.coordinate_proj = context.coordinate_proj
        self.hidden_patch_size = int(context.hidden_patch_size)
        self.latent_patch_size = int(context.latent_patch_size)
        self.unit_len = self.hidden_patch_size + self.latent_patch_size
        self.hidden_size = int(context.hidden_size)
        self.attn_backend = attn_backend
        self.fm_sigma = float(context.fm_sigma)

        attn0 = self.dit.blocks[0].attn
        self.num_heads = int(attn0.num_heads)
        self.head_dim = int(attn0.head_dim)
        self.num_layers = len(self.dit.blocks)

        current_latent_start = self.unit_len + self.hidden_patch_size
        self.current_latent_slice = slice(
            current_latent_start, current_latent_start + self.latent_patch_size
        )

    def _run_cached_blocks(
        self,
        x: torch.Tensor,
        *,
        all_mods: torch.Tensor,
        cache_k: torch.Tensor,
        cache_v: torch.Tensor,
        block_mask: Any | None,
        sdpa_mask: torch.Tensor | None,
        rotary_cos: torch.Tensor,
        rotary_sin: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        branch_batch = x.size(0)
        new_k = torch.empty(
            self.num_layers,
            branch_batch,
            self.num_heads,
            self.unit_len,
            self.head_dim,
            device=x.device,
            dtype=x.dtype,
        )
        new_v = torch.empty_like(new_k)
        use_flex = self.attn_backend == "flex"
        if use_flex and block_mask is None:
            raise ValueError("Flex attention backend requires a BlockMask.")

        def attention(layer_idx: int, block: nn.Module, attn_in: torch.Tensor):
            out, k, v = project_attention(
                block.attn,
                attn_in,
                num_heads=self.num_heads,
                head_dim=self.head_dim,
                rotary_cos=rotary_cos,
                rotary_sin=rotary_sin,
                key_prefix=cache_k[layer_idx],
                value_prefix=cache_v[layer_idx],
                block_mask=block_mask if use_flex else None,
                attn_mask=sdpa_mask,
                dropout_p=0.0,
            )
            new_k[layer_idx].copy_(k[:, :, : self.unit_len, :])
            new_v[layer_idx].copy_(v[:, :, : self.unit_len, :])
            return out

        x, final_mod = self.dit.run_modulated_blocks(
            x=x, all_mods=all_mods, attention=attention
        )
        velocity = self.dit.apply_final_layer(
            x[:, self.current_latent_slice], final_mod
        )
        return velocity, new_k, new_v

    def forward(
        self,
        z: torch.Tensor,
        *,
        prev_unit: torch.Tensor,
        current_hidden: torch.Tensor,
        all_mods: torch.Tensor,
        cache_k: torch.Tensor,
        cache_v: torch.Tensor,
        rotary_cos: torch.Tensor,
        rotary_sin: torch.Tensor,
        t: torch.Tensor | None = None,
        cfg_prev_unit: torch.Tensor | None = None,
        cfg_current_hidden: torch.Tensor | None = None,
        guidance_scale: torch.Tensor | None = None,
        block_mask: Any | None = None,
        sdpa_mask: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        has_cfg = cfg_prev_unit is not None
        if has_cfg != (cfg_current_hidden is not None):
            raise ValueError(
                "NextPatchStep CFG requires both cfg_prev_unit and cfg_current_hidden."
            )
        batch_size = current_hidden.size(0)
        z_proj = self.coordinate_proj(z)
        x = concat_branches(
            [prev_unit, current_hidden, z_proj],
            ([cfg_prev_unit, cfg_current_hidden, z_proj] if has_cfg else None),
        )
        vt, new_k, new_v = self._run_cached_blocks(
            x,
            all_mods=all_mods,
            cache_k=cache_k,
            cache_v=cache_v,
            block_mask=block_mask,
            sdpa_mask=sdpa_mask,
            rotary_cos=rotary_cos,
            rotary_sin=rotary_sin,
        )
        del t
        if not has_cfg:
            return vt, new_k, new_v
        if guidance_scale is None:
            raise ValueError("FlowMatching NextPatchStep requires guidance_scale.")
        velocity = apply_cfg(vt, batch_size=batch_size, guidance=guidance_scale)
        return velocity, new_k, new_v


===== FirstPatchStep =====
class FirstPatchStep(nn.Module):
    """First patch of a decode: no prev unit, no KV cache, no history."""

    def __init__(self, context: DiTInferenceContext):
        super().__init__()
        self.dit = context.dit
        self.coordinate_proj = context.coordinate_proj
        self.hidden_patch_size = int(context.hidden_patch_size)
        self.latent_patch_size = int(context.latent_patch_size)
        self.hidden_size = int(context.hidden_size)
        self.fm_sigma = float(context.fm_sigma)

    def forward(
        self,
        z: torch.Tensor,
        *,
        current_hidden: torch.Tensor,
        all_mods: torch.Tensor,
        t: torch.Tensor | None = None,
        cfg_current_hidden: torch.Tensor | None = None,
        guidance_scale: torch.Tensor | None = None,
    ) -> torch.Tensor:
        del t
        batch_size = current_hidden.size(0)
        z_proj = self.coordinate_proj(z)
        x = concat_branches(
            [current_hidden, z_proj],
            ([cfg_current_hidden, z_proj] if cfg_current_hidden is not None else None),
        )
        vt = self.dit.run_blocks(x=x, all_mods=all_mods)
        vt = vt[:, self.hidden_patch_size :]
        if cfg_current_hidden is None:
            return vt
        if guidance_scale is None:
            raise ValueError("FlowMatching current step requires guidance_scale.")
        return apply_cfg(vt, batch_size=batch_size, guidance=guidance_scale)

## Phase 2 — Cached Step Findings

`NextPatchStep` confirms how the optimized path avoids recomputing
historical attention state.

For each transformer layer, cached prefix keys and values are passed into
attention through:

- `key_prefix=cache_k[layer_idx]`
- `value_prefix=cache_v[layer_idx]`

Only K/V for the current/new unit are produced as `new_k` and `new_v`.

Dynamic work that still occurs every NFE step:
- `coordinate_proj(z)`
- construction of the current local input
- transformer block computation for the current/recent unit
- final velocity prediction

Reusable state:
- historical prefix K/V
- masks
- rotary embeddings
- precomputed per-NFE modulation state

`FirstPatchStep` does not use a KV cache because no historical prefix
exists yet.

Main conclusion:
The cached path targets the expensive DiT computation by preventing
historical attention state from being recomputed at every NFE step.